bot_config:
    bot_name: Hyena # your bot's name
    bot_description: The customisable and self hostable Hyena. # your bot's description'
    bot_prefix: "-" # your bot's prefix in quotation marks 
    owners_id: # the IDs of the owners of the bots
        - 711444754080071714
        - 832660720495362078
        - 918703165648539700
        - 921020428791742515
    cogs_not_to_load: 
        - ""
    # add cogs which you dont want to use in a list for example:
    # cogs_not_to_load: 
    #     - "file_name_of_cog.py"
    #     - "file_name_of_cog2.py" 
    # etc.....
    mod_action_logs_channel: 814895166141628426 # the channel to get moderation action logs errors eg. ban/kick etc.
    errors_channel: 814895166141628426 # the secret channel to get bot errors
    errors_channel: 932723576409301086 #814895166141628426 # the secret channel to get bot errors

    statuses: # statuses you want to be displayed in your bot
        - with the ban hammer!
        - hey I'm the new and improved hostable hyena!
        - https://github.com/Hyena-Bot
    guild_id: 932723575775965254 # your server's ID
    colors:              # theme color of the bot (you will see them in the embeds) (in python hex format)
        - "0x3A4047"
        - "0xFFFDFC"
    success_emoji: "<:ttt:932956998742462475>" # any success/verified emoji in your server that looks good
    # here's a good one-
    # https://cdn.discordapp.com/emojis/905905851489988718.webp?size=96&quality=lossless
    
    failure_emoji: "❌" # default x mark emoji

automod_config:
    spam: true
    spam_messages_back_to_back: 5 # Threshold cap
    spam_message_word_limit: 500 # Words/message

    badwords: true
    custom_badwords:
        - null # replace null with the badword needed. Most are already provided

    caps: true
    caps_threshold: 80 

    invites: true

    phish: true

    warn_message: "Please refrain from sending rule breaking messages $mention."
    embed_warn_message: true
    delete_message_after: 5
    
    ignored_channels:
        - null # add the channel ids, where automod will be ignored.
